language: ruby
cache: bundler
rvm:
  - 2.2.3
env:
  - DATABASE_URL=mysql2://root@127.0.0.1:3306/wca_test
before_install:
  - cd WcaOnRails/
before_script:
  - bundle exec rake db:create
sudo: false
script:
  - rake
  - bundle exec pre-commit run git
