dist: trusty
language: ruby
os: linux
cache:
  directories:
    - $HOME/.phantomjs
    - $HOME/.bundle
    - WcaOnRails/node_modules
  yarn: true
env:
  global:
    - DATABASE_URL=mysql2://root:@127.0.0.1:3306/wca_test
    - RACK_ENV=test
before_install:
  # Workaround for https://github.com/travis-ci/travis-ci/issues/8978
  - yes | gem update --system
  - yes | gem update bundler

  - nvm install 12
  - nvm use 12

  # From https://yarnpkg.com/en/docs/install-ci#travis-tab
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=1.22.4-1

  - cd WcaOnRails/
before_script:
  - bundle exec rake db:reset
  # See https://github.com/usabilityhub/rails-erb-loader/issues/63#issuecomment-374791504
  # and our https://github.com/thewca/worldcubeassociation.org/issues/3476
  - DISABLE_SPRING=1 bundle exec rake assets:precompile
script:
  - bundle exec overcommit --sign && bundle exec overcommit --sign pre-commit && (cd .. && BUNDLE_GEMFILE=WcaOnRails/Gemfile bundle exec overcommit --run)
  - bundle exec rake
