language: ruby
cache:
  directories:
    - WcaOnRails/vendor/bundle
rvm:
  - 2.3.1
env:
  global:
    - DATABASE_URL=mysql2://root@127.0.0.1:3306/wca_test
    - PATH=$HOME/.local/bin:$PATH
before_install:
  - gem install bundler
  # The Stripe API requires a newer version of openssl
  - sudo apt-get update && sudo apt-get install --only-upgrade openssl
  - cd WcaOnRails/
before_script:
  - bundle exec rake db:reset RAILS_ENV=test
sudo: required
script:
  - bundle exec pre-commit run git
  - bundle exec rubocop
  - bundle exec rake
