dist: trusty
sudo: false
language: ruby
rvm:
  - 2.5.0
bundler_args: --path $HOME/.bundle
cache:
  directories:
    - $HOME/.phantomjs
    - $HOME/.bundle
    - WcaOnRails/node_modules
  yarn: true
env:
  global:
    - DATABASE_URL=mysql2://root:@127.0.0.1:3306/wca_test
    - RACK_ENV=test
before_install:
  - nvm install 8
  - nvm use 8

  # From https://yarnpkg.com/en/docs/install-ci#travis-tab
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

  - cd WcaOnRails/
before_script:
  - bundle exec rake db:reset
  - bundle exec rake assets:precompile
script:
  - bundle exec pre-commit run git
  - bundle exec rubocop
  - bundle exec rake
